site_name: Nava Platform CLI
repo_url: https://github.com/navapbc/platform-cli
repo_name: navapbc/platform-cli

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.svg
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - navigation.sections
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - github-callouts
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - footnotes

plugins:
  - autorefs
  - awesome-nav:
      filename: ".nav.yaml"
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # Mostly following:
          # https://mkdocstrings.github.io/python/usage/#recommended-settings
          options:
            preload_modules:
              - copier

            docstring_section_style: spacy

            # CROSS-REFERENCES -------------------------------------------------------
            # Enable cross-references in signatures.
            signature_crossrefs: true

            # Unwrap actual types from `Annotated` type annotations.
            unwrap_annotated: true

            # MEMBERS ----------------------------------------------------------------
            # Show class inherited members.
            inherited_members: true

            # Render auto-generated summaries of attributes, functions, etc.
            # at the start of each symbol's documentation.
            summary: true

            # HEADINGS ---------------------------------------------------------------
            heading_level: 1
            parameter_headings: true
            type_parameter_headings: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true

            # SIGNATURES -------------------------------------------------------------
            line_length: 88

            # Merge signature and docstring of `__init__` methods
            # into their parent class signature and docstring.
            merge_init_into_class: true

            # Render signatures and attribute values in a separate code block,
            # below the symbol heading.
            separate_signature: true

            # Show type annotations in signatures.
            show_signature_annotations: true

            # Show type parameters in signatures.
            show_signature_type_parameters: true

            # OTHER ------------------------------------------------------------------
            # Show base classes
            show_bases: false
  - search
  - redirects:
      redirect_maps:
        'getting-started/new-project.md': 'guides/new-project.md'
        'getting-started/migrating-from-legacy-template.md': 'guides/migrating-from-legacy-template.md'
        'avoiding-conflicts-on-update.md': 'guides/avoiding-conflicts-on-update.md'
        'how-it-works.md': 'reference/how-templates-work.md'
        'adding-an-app.md': 'guides/adding-an-app.md'
        'updating.md': 'guides/updating.md'

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
