site_name: Nava Platform CLI
repo_url: https://github.com/navapbc/platform-cli
repo_name: navapbc/platform-cli

theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.svg
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.top
    - navigation.tracking
  palette:
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - github-callouts
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
  - footnotes

plugins:
  - autorefs
  - awesome-pages
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            preload_modules:
              - copier
  - search

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
