[tool.poetry]
name = "nava-platform-cli"
version = "0.1.0"
description = "Nava PBC's Platform CLI tool for managing platform templates"
authors = ["Your Name <you@example.com>"]
license = "Apache License Version 2.0"
readme = "README.md"
packages = [{ include = "nava" }]

[tool.poetry.dependencies]
python = "^3.11"
click = "^8.1.7"
copier = "^9.3.1"
pyyaml = "^6.0.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-watch = "^4.2.0"
mypy = "^1.11.2"
types-pyyaml = "^6.0.12.20240917"

[tool.poetry.scripts]
platform = "nava.cli:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
