name: "Configure git"
description: "Configure basic things to enable git usage in a GitHub Action"
runs:
  using: "composite"
  steps:
      - name: Configure git
        shell: bash
        run: |
          git config --global user.name nava-platform-bot
          git config --global user.email platform-admins@navapbc.com
