#!/usr/bin/env bash
#
# Simple, but more-or-less complete run through of core functionality. Doesn't
# really check that things are *correct*, just that they run without unexpected
# errors.

set -xeuo pipefail

#######################
# Setup
#######################

source "$(realpath "$(dirname "${BASH_SOURCE[0]}")")/common.sh"

init_project_dir

#######################
# Test
#######################

$CMD --help

# TODO: add --data-file support to CLI and have as many of these
# settings in more maintainable separate file
$CMD infra install \
    --commit \
    --data base_project_name="${PROJECT_NAME}" \
    --data base_owner=platform-admins \
    --data base_code_repository_url=https://foo.example \
    --data base_default_region=us-east-1 \
    --data app_name=rails \
    --data app_local_port=3000 \
    --data app_has_dev_env_setup=true \
    "${PROJECT_DIR}"

$CMD infra info "${PROJECT_DIR}"

$CMD infra update "${PROJECT_DIR}"
$CMD infra update \
    --answers-only \
    --data base_owner=platform-admins2 \
    --data app_local_port=2900 \
    "${PROJECT_DIR}"
$CMD infra update --force "${PROJECT_DIR}"
$CMD infra update-base \
    --answers-only \
    --data base_code_repository_url=https://example.foo \
    "${PROJECT_DIR}"
$CMD infra update-base \
    --force \
    "${PROJECT_DIR}"
# no actual changes
$CMD infra update-app \
    --answers-only \
    --data base_owner=platform-admins3 \
    "${PROJECT_DIR}" \
    rails
$CMD infra update-app \
    --force \
    "${PROJECT_DIR}" \
    rails

{ yes || true; } | $CMD app install \
    --template-uri https://github.com/navapbc/template-application-rails \
    --commit \
    "${PROJECT_DIR}" \
    rails \
    --data app_local_port=3000

$CMD app update \
    --template-uri https://github.com/navapbc/template-application-rails \
    "${PROJECT_DIR}" \
    rails

$CMD app update \
    --answers-only \
    --data app_local_port=3100 \
    "${PROJECT_DIR}" \
    rails

$CMD app update \
    --force \
    "${PROJECT_DIR}" \
    rails

for app_template in flask nextjs; do
    $CMD infra add-app \
        --commit \
        --data app_name="${app_template}" \
        --data app_local_port=3000 \
        --data app_has_dev_env_setup=true \
        "${PROJECT_DIR}" \
        ${app_template}

    { yes || true; } | $CMD app install \
        --template-uri https://github.com/navapbc/template-application-"${app_template}" \
        --commit \
        "${PROJECT_DIR}" \
        "${app_template}" \
        --data app_local_port=3000

    $CMD app update \
        --template-uri https://github.com/navapbc/template-application-"${app_template}" \
        "${PROJECT_DIR}" \
        "${app_template}"

    $CMD app update \
        --answers-only \
        --data app_local_port=3100 \
        "${PROJECT_DIR}" \
        "${app_template}"
done

$CMD infra info "${PROJECT_DIR}"
