name: Template for CI (container)

on:
  workflow_call:
    inputs:
      container_cmd:
        required: true
        type: string

permissions:
  contents: read

env:
  CONTAINER_CMD: ${{ inputs.container_cmd }}

jobs:
  build-and-run:
    name: Build and run
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/configure-git

      - name: Build
        run: make build

      - name: Run --help
        run: ${CONTAINER_CMD} run --rm nava-platform-cli --help

      - name: Run e2e through container-wrapper
        env:
          CMD: ./bin/container-wrapper
        run: make test-e2e
