name: CI (nix)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    uses: ./.github/workflows/ci-nix-template.yml
    with:
      os: ${{ matrix.os }}
