name: CI (pipx)

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

permissions:
  contents: read

jobs:
  install:
    name: Install with pipx
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: ./.github/actions/configure-git
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install with pipx
        run: |
          pipx install --python "$(which python)" .

          # list which versions of dependencies where resolved, for debugging
          echo "::group::Installed dependencies"
          pipx runpip nava-platform-cli list
          echo "::endgroup::"

      - name: Run --help
        run: nava-platform --help

      - name: Run e2e
        run: make test-e2e
