name: CI (python)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [ubuntu-latest, macos-latest]

    uses: ./.github/workflows/ci-py-template.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
