name: CI (pipx)

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  install:
    name: Install with pipx
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/configure-git
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install with pipx
        run: |
          pipx install --python "$(which python)" .

          # list which versions of dependencies where resolved, for debugging
          echo "::group::Installed dependencies"
          pipx runpip nava-platform-cli list
          echo "::endgroup::"

      - name: Run --help
        run: nava-platform --help

      - name: Run e2e
        run: make test-e2e
