name: CI (pipx)

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string

permissions:
  contents: read

jobs:
  install:
    name: Install with pipx
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: ./.github/actions/configure-git
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install with pipx
        run: |
          pipx install --python "$(which python)" .

          # list which versions of dependencies where resolved, for debugging
          echo "::group::Installed dependencies"
          pipx runpip nava-platform-cli list
          echo "::endgroup::"

      - name: Run --help
        run: nava-platform --help

      - name: Run e2e
        run: make test-e2e

      - name: Upload logs on failure
        if: failure()
        uses: ./.github/actions/upload-cli-logs
